/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kupacdesktop.ui;

import java.awt.Color;
import java.awt.GridLayout;
import java.text.SimpleDateFormat;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JLabel;
import kupacdesktop.Navigator;
import kupacdesktop.Strings;
import kupacdesktop.Utils;
import kupacdesktop.network.MockDatabaseService;
import kupacdesktop.network.dto.RequestInfoDTO;
import kupacdesktop.network.dto.UserDTO;

/**
 *
 * @author milos
 */
public class FinishedRequestScreen extends javax.swing.JFrame {

    private static final String TAG = FinishedRequestScreen.class.getSimpleName();

    private static RequestInfoDTO requestInfo;

    /**
     * Creates new form EditInfoScreen
     */
    public FinishedRequestScreen(RequestInfoDTO requestInfo) {
        setTitle(Strings.APP_NAME);
        initComponents();
        setVisible(true);
        setResizable(false);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        getContentPane().setBackground(new java.awt.Color(0xa9a9a9));

        FinishedRequestScreen.requestInfo = requestInfo;

        setupScreen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        leaveRating = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        labelFirstAndLastName = new javax.swing.JLabel();
        labelJob = new javax.swing.JLabel();
        labelPhone = new javax.swing.JLabel();
        labelAddress = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        labelPrice = new javax.swing.JLabel();
        labelRating = new javax.swing.JLabel();
        labelExperience = new javax.swing.JLabel();
        scrollPane1 = new java.awt.ScrollPane();
        specTechPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelDateInterval = new javax.swing.JLabel();
        labelPayment = new javax.swing.JLabel();
        leaveComment = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Navigacija = new javax.swing.JMenu();
        mainScreen = new javax.swing.JMenuItem();
        activeRequests = new javax.swing.JMenuItem();
        finishedRequests = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        changeInfo = new javax.swing.JMenuItem();
        changePassword = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Telefon:");

        jLabel4.setText("Adresa:");

        jLabel3.setText("Posao:");

        jLabel2.setText("Ime i prezime:");

        leaveRating.setBackground(new java.awt.Color(0, 0, 0));
        leaveRating.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        leaveRating.setForeground(new java.awt.Color(255, 255, 255));
        leaveRating.setText("OCENI");
        leaveRating.setToolTipText("");
        leaveRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveRatingActionPerformed(evt);
            }
        });

        jLabel6.setText("Cena:");

        labelFirstAndLastName.setText("Petar Petrovic");

        labelJob.setText("moler");

        labelPhone.setText("0641234567");

        labelAddress.setText("Takovska 1");

        jLabel11.setText("Prosecna ocena:");

        jLabel12.setText("Iskustvo:");

        jLabel13.setText("Specijalne tehnike:");

        labelPrice.setText("1200 din");

        labelRating.setText("4.56");

        labelExperience.setText("7 godina");

        javax.swing.GroupLayout specTechPanelLayout = new javax.swing.GroupLayout(specTechPanel);
        specTechPanel.setLayout(specTechPanelLayout);
        specTechPanelLayout.setHorizontalGroup(
            specTechPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );
        specTechPanelLayout.setVerticalGroup(
            specTechPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        scrollPane1.add(specTechPanel);

        jLabel8.setText("Period radova:");

        jLabel7.setText("Nacin placanja:");

        labelDateInterval.setText("1.2.2019. - 3.2.2019.");

        labelPayment.setText("gotovina");

        leaveComment.setBackground(new java.awt.Color(0, 0, 0));
        leaveComment.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        leaveComment.setForeground(new java.awt.Color(255, 255, 255));
        leaveComment.setText("OSTAVI KOMENTAR");
        leaveComment.setToolTipText("");
        leaveComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveCommentActionPerformed(evt);
            }
        });

        Navigacija.setText("Navigacija");

        mainScreen.setText("Glavni ekran");
        mainScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainScreenActionPerformed(evt);
            }
        });
        Navigacija.add(mainScreen);

        activeRequests.setText("Aktivni zahtevi");
        activeRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activeRequestsActionPerformed(evt);
            }
        });
        Navigacija.add(activeRequests);

        finishedRequests.setText("Zavrseni zahtevi");
        finishedRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishedRequestsActionPerformed(evt);
            }
        });
        Navigacija.add(finishedRequests);
        Navigacija.add(jSeparator1);

        changeInfo.setText("Izmeni licne podatke");
        changeInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeInfoActionPerformed(evt);
            }
        });
        Navigacija.add(changeInfo);

        changePassword.setText("Promeni lozinku");
        changePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordActionPerformed(evt);
            }
        });
        Navigacija.add(changePassword);

        logout.setText("Odjavi se");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        Navigacija.add(logout);

        jMenuBar1.add(Navigacija);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelJob)
                            .addComponent(labelFirstAndLastName)
                            .addComponent(labelAddress)
                            .addComponent(labelPhone)
                            .addComponent(labelPrice)
                            .addComponent(labelExperience)
                            .addComponent(labelRating)
                            .addComponent(labelDateInterval)
                            .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPayment))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(leaveRating, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addComponent(leaveComment, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelFirstAndLastName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labelJob))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(labelAddress))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(labelPhone))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(labelPrice))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(labelRating))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(labelExperience))
                        .addGap(46, 46, 46)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(labelDateInterval))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(labelPayment))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leaveRating, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leaveComment, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void leaveRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveRatingActionPerformed
        String ratingText = Utils.inputTextDialog(this, "Slanje ocene", "Unesite ocenu od 1 do 5");
        Double rate = null;
        try {
            rate = Double.parseDouble(ratingText);
            if (rate < 1 || rate > 5) {
                throw new Exception("Invalid rate value");
            }
        } catch (Exception e) {
            Utils.displayErrorDialog(this, "Slanje ocene", "Format unete ocene nije validan.");
            return;
        }

        try {
            MockDatabaseService.getInstance().sendRate(requestInfo, rate);
            requestInfo.setRateSent(true);

            leaveRating.setEnabled(false);
            leaveRating.setBackground(Color.DARK_GRAY);
            Utils.displaySuccessDialog(this, "Slanje ocene", "Slanje ocene je uspesno!");
        } catch (Exception ex) {
            Utils.displayErrorDialog(this, "Slanje ocene", "Slanje ocene nije uspesno.");
        }
    }//GEN-LAST:event_leaveRatingActionPerformed

    private void mainScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainScreenActionPerformed
        Navigator.openMainScreen(this);
    }//GEN-LAST:event_mainScreenActionPerformed

    private void activeRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activeRequestsActionPerformed
        Navigator.openActiveRequestsScreen(this);
    }//GEN-LAST:event_activeRequestsActionPerformed

    private void finishedRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishedRequestsActionPerformed
        Navigator.openFinishedRequestsScreen(this);
    }//GEN-LAST:event_finishedRequestsActionPerformed

    private void changeInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeInfoActionPerformed
        Navigator.openChangeInfoScreen(this);
    }//GEN-LAST:event_changeInfoActionPerformed

    private void changePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordActionPerformed
        Navigator.openChangePasswordScreen(this);
    }//GEN-LAST:event_changePasswordActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        if (Utils.displayYesNoScreen(this, "Odjava", "Da li ste sigurni da zelite da se odjavite?")) {
            Navigator.logout(this);
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void leaveCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveCommentActionPerformed
        String comment = Utils.inputTextDialog(this, "Slanje komentara", "Unesite komentar");
        if (comment == null || comment.isEmpty()) {
            Utils.displayErrorDialog(this, "Slanje komentara", "Neispravan format komentara.");
            return;
        }

        try {
            MockDatabaseService.getInstance().sendComment(requestInfo, comment);
            requestInfo.setCommentSent(true);

            leaveComment.setEnabled(false);
            leaveComment.setBackground(Color.DARK_GRAY);
            Utils.displaySuccessDialog(this, "Slanje komentara", "Slanje komentara je uspesno!");
        } catch (Exception ex) {
            Utils.displayErrorDialog(this, "Slanje komentara", "Slanje komentara nije uspesno.");
        }
    }//GEN-LAST:event_leaveCommentActionPerformed

    private void setupScreen() {
        UserDTO repairman = requestInfo.getRepairman();
        labelFirstAndLastName.setText(repairman.getFirstName() + " " + repairman.getLastName());
        labelAddress.setText(repairman.getAddress());
        labelPhone.setText(repairman.getPhoneNumber());
        labelExperience.setText(repairman.getExperience() + " godina");
        labelPrice.setText(repairman.getPrice() + " din");
        labelJob.setText(repairman.getJob());
        labelRating.setText(String.format("%.2f", repairman.getRating()));

        if (repairman.getSpecialTechniques() != null) {
            List<String> techniques = new LinkedList<>();
            for (String t : repairman.getSpecialTechniques()) {
                String[] arr = t.split(",");
                for (String tt : arr) {
                    techniques.add(tt.replaceAll(" ", ""));
                }
            }
            specTechPanel.setLayout(new GridLayout(techniques.size(), 1));
            for (String technique : techniques) {
                JLabel label = new JLabel(technique, JLabel.CENTER);
                //label.setBorder(BorderFactory.createLineBorder(Color.BLACK));
                specTechPanel.add(label);
            }
        } else {
            specTechPanel.setLayout(new GridLayout());
        }

        SimpleDateFormat format = new SimpleDateFormat("dd.MM.yyyy.");
        String dateBegin = format.format(requestInfo.getDateBegin());
        String dateEnd = format.format(requestInfo.getDateEnd());

        labelDateInterval.setText(dateBegin + " - " + dateEnd);
        labelPayment.setText(requestInfo.getPaymentMethod());

        if (requestInfo.isCommentSent()) {
            leaveComment.setEnabled(false);
            leaveComment.setBackground(Color.DARK_GRAY);
        }
        if (requestInfo.isRateSent()) {
            leaveRating.setEnabled(false);
            leaveRating.setBackground(Color.DARK_GRAY);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Navigacija;
    private javax.swing.JMenuItem activeRequests;
    private javax.swing.JMenuItem changeInfo;
    private javax.swing.JMenuItem changePassword;
    private javax.swing.JMenuItem finishedRequests;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel labelAddress;
    private javax.swing.JLabel labelDateInterval;
    private javax.swing.JLabel labelExperience;
    private javax.swing.JLabel labelFirstAndLastName;
    private javax.swing.JLabel labelJob;
    private javax.swing.JLabel labelPayment;
    private javax.swing.JLabel labelPhone;
    private javax.swing.JLabel labelPrice;
    private javax.swing.JLabel labelRating;
    private javax.swing.JButton leaveComment;
    private javax.swing.JButton leaveRating;
    private javax.swing.JMenuItem logout;
    private javax.swing.JMenuItem mainScreen;
    private java.awt.ScrollPane scrollPane1;
    private javax.swing.JPanel specTechPanel;
    // End of variables declaration//GEN-END:variables
}
